### ISSUE TITLE
First Slide Blank in Audience View

### ISSUE THREAD

**Issue by jongoodnow** [OsvaldoRosado/Firefly#48]
When first navigating to the audience view, the slide shown is blank. If the presenter hits Previous or Next, the issue is resolved and the viewer can see the slide correctly. But if the presenter goes back to the first slide and the audience member navigates to the Q&A or Submit view and then goes back to the live view, the slide is blank again.

**Comment by KeatonTech** [comment]
We had this issue last night and it magically went away when we tried to fix it. Prevailing theory is that the first image takes excessively long to load. In most cases if you let it sit there for like 20 seconds it will eventually show up.

**Comment by jongoodnow** [comment]
In my experience, it doesn't show up at all.
