### ISSUE TITLE
Slide count returned by GetPresentation is too high

### ISSUE THREAD

**Issue by jongoodnow** [OsvaldoRosado/Firefly#55]
It's 29 instead of 20 on the CRC cards presentation. Urls are in in the slideUrls that 404 because the images for those slides don't exist.

**Comment by OsvaldoRosado** [comment]
Fixed in https://github.com/OsvaldoRosado/FireflyProcessing/commit/9e013e12faebe12b26f6bc8b6a897f73d0f2bd1e
