### ISSUE TITLE
PowerPoint uploads sometimes fail

### ISSUE THREAD

**Issue by KeatonTech** [OsvaldoRosado/Firefly#59]
Not sure why, it might just be related to file size. The failure seems to happen almost immediately

**Comment by OsvaldoRosado** [comment]
Fixed in 
https://github.com/OsvaldoRosado/FireflyProcessing/commit/d564309ac0381e235418ebd86db31c631b4c1f13
https://github.com/OsvaldoRosado/FireflyProcessing/commit/849228dd43f9f6a56e52b7f3b7c67cec0744f69e
